# Generated by Django 3.2.20 on 2023-09-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workers',
            name='Gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
