# Generated by Django 3.2.20 on 2023-09-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0003_assign_product_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryboy',
            name='SHOP_ID',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Worker_Rental_SystemApp.shop'),
            preserve_default=False,
        ),
    ]
