# Generated by Django 3.2.20 on 2023-09-23 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0004_deliveryboy_shop_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='USER_ID',
        ),
        migrations.AddField(
            model_name='productrequest',
            name='LOGIN_ID',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='Worker_Rental_SystemApp.login'),
            preserve_default=False,
        ),
    ]
