# Generated by Django 3.2.20 on 2023-09-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0005_auto_20230923_1152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productrequest',
            name='LOGIN_ID',
        ),
    ]
