# Generated by Django 3.2.20 on 2023-09-23 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0006_remove_productrequest_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='LOGIN_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Worker_Rental_SystemApp.login'),
            preserve_default=False,
        ),
    ]
