# Generated by Django 3.2.20 on 2023-09-23 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0007_productrequest_login_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='PRODUCT_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Worker_Rental_SystemApp.product'),
            preserve_default=False,
        ),
    ]
