# Generated by Django 3.2.20 on 2023-09-25 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0008_ratings_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='USER_ID',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='WORKER_ID',
        ),
        migrations.AddField(
            model_name='chat',
            name='FROM_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fid', to='Worker_Rental_SystemApp.login'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat',
            name='TO_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tid', to='Worker_Rental_SystemApp.login'),
            preserve_default=False,
        ),
    ]
