# Generated by Django 3.2.20 on 2023-10-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0009_auto_20230925_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assign',
            name='PRODUCT_ID',
        ),
    ]
