# Generated by Django 3.2.20 on 2023-10-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0010_remove_assign_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrequest',
            name='Latitude',
            field=models.FloatField(default=11.4567),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrequest',
            name='Longitude',
            field=models.FloatField(default=76.34567),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productrequest',
            name='address',
            field=models.CharField(default=234567, max_length=500),
            preserve_default=False,
        ),
    ]
