# Generated by Django 3.2.20 on 2023-10-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0011_auto_20231003_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('DELIVERY_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Worker_Rental_SystemApp.deliveryboy')),
            ],
        ),
    ]
