# Generated by Django 3.2.20 on 2023-10-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0012_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Complaints',
            field=models.DateField(),
        ),
    ]
