# Generated by Django 3.2.20 on 2023-10-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0014_auto_20231020_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='Longitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
