# Generated by Django 3.2.20 on 2023-10-20 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Worker_Rental_SystemApp', '0015_auto_20231020_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='Complaints',
            field=models.CharField(max_length=100),
        ),
    ]
